easy_admin:
  site_name: 'Les Poteries de Josette'
  design:
    menu:
      - {label: 'Catégories'}
      - {entity: 'Product', icon: 'user'}
      - {entity: 'Event', icon: 'calendar'}
      - {entity: 'Blog', icon: 'heart'}
      - {entity: 'Recipe', icon: 'utensils'}
      - {label: 'Configuration'}
      - {entity: 'BlogType', icon: 'cog'}
      - {entity: 'RecipeCategory', icon: 'cog'}
      - { label: 'Retour au site web', route: 'home', icon: 'reply'}
  list:
    max_results: 20
  entities:
    Product:
      class: App\Entity\Product
      label: 'Mes poteries'
      list:
        title: 'Les poteries de Josette'
        fields:
          - {property: 'title', type: 'text'}
          - {property: 'description', type: 'text'}
          - {property: 'imageFile', template: 'vich_uploader_image.html.twig'}
      form:
        title: 'Les poteries de Josette'
        fields:
          - {property: 'title', type: 'text'}
          - {property: 'description'}
          - {property: 'imageFile', type: 'vich_image'}

    Event:
      class: App\Entity\Event
      label: 'Mes évènements'
      list:
        title: 'Les évènements de Josette'
        fields:
          - {property: 'title', type: 'text'}
          - {property: 'description', type: 'text'}
          - {property: 'location', type: 'text'}
          - {property: 'link', type: 'text'}
          - {property: 'dateStart', type: 'date'}
          - {property: 'dateEnd', type: 'date'}
          - {property: 'imageFile', template: 'vich_uploader_image.html.twig'}
      form:
        title: 'Les poteries de Josette'
        fields:
          - {property: 'title', type: 'text'}
          - {property: 'description'}
          - {property: 'location', type: 'text'}
          - {property: 'link', type: 'text'}
          - {property: 'dateStart', type: 'date'}
          - {property: 'dateEnd', type: 'date'}
          - {property: 'imageFile', type: 'vich_image'}

    Recipe:
      class: App\Entity\Recipe
      label: 'Mes recettes'
      list:
        title: 'Les recettes de Josette'
        fields:
          - {property: 'name', type: 'text'}
          - category
          - {property: 'description', type: 'text'}
          - {property: 'ingredient', type: 'text'}
          - {property: 'imageFile', template: 'vich_uploader_image.html.twig'}
      form:
        title: 'Les poteries de Josette'
        help: 'Attention, les ingrédients doivent être séparés par une virgule'
        fields:
          - {property: 'name', type: 'text'}
          - category
          - {property: 'description'}
          - {property: 'ingredient'}
          - {property: 'imageFile', type: 'vich_image'}

    Blog:
      class: App\Entity\Blog
      label: 'Coups de coeur'
      list:
        title: 'Mes coups de coeur'
        fields:
          - {property: 'name', type: 'text'}
          - {property: 'description', type: 'text'}
          - {property: 'location', type: 'text'}
          - {property: 'url', type: 'text'}
          - type
      form:
        title: 'Mes coups de coeur'
        fields:
          - {property: 'name', type: 'text'}
          - description
          - {property: 'location', type: 'text'}
          - {property: 'url', type: 'text'}
          - type

    BlogType:
      class: App\Entity\BlogType
      label: 'Types de coups de coeur'
      list:
        title: 'Types'
        fields:
          - {property: 'name', type: 'text'}
      form:
        title: 'Types'
        fields:
          - {property: 'name', type: 'text'}

    RecipeCategory:
      class: App\Entity\RecipeCategory
      label: 'Catégories de recettes'
      list:
        title: 'Catégories'
        fields:
          - {property: 'name', type: 'text'}
      form:
        title: 'Catégories'
        fields:
          - {property: 'name', type: 'text'}


